{
    "topic": "App Commands Errors",
    "pageNumber": "1",
    "type": "App Error - Contribution Not Sent",
    "definition": {
        "text": "There was a problem trying to send your contribution to your fork of the Superalgos repository, or from your fork to the Superalgos/Superalgos main repository.",
        "updated": 1611129378492
    },
    "paragraphs": [
        {
            "style": "Text",
            "text": "Check the following section for details on what may have happened. After you fix the issue that prevented the App Contribute Command to run, you may try again.",
            "updated": 1611152997869
        },
        {
            "style": "Title",
            "text": "Error Info",
            "updated": 1611154606702
        },
        {
            "style": "Text",
            "text": "In the following section, you will find the information recorded when the error occurred."
        },
        {
            "style": "Note",
            "text": "You will only see the information if you opened this page as a result of the error actually occurring.",
            "updated": 1611153032408
        },
        {
            "style": "Subtitle",
            "text": "Error Message"
        },
        {
            "style": "Text",
            "text": "The following is the Error Message of the Exception that occured at the Client:"
        },
        {
            "style": "Placeholder",
            "text": "errorMessage"
        },
        {
            "style": "Subtitle",
            "text": "Error Stack"
        },
        {
            "style": "Text",
            "text": "The following is the Error Stack of the Exception that occured at the Client:"
        },
        {
            "style": "Placeholder",
            "text": "errorStack"
        },
        {
            "style": "Subtitle",
            "text": "Error Code"
        },
        {
            "style": "Text",
            "text": "The following is the Error Code of the Exception that occured at the Client:"
        },
        {
            "style": "Placeholder",
            "text": "errorCode"
        },
        {
            "style": "Subtitle",
            "text": "Error Details",
            "updated": 1611154543778
        },
        {
            "style": "Text",
            "text": "The following are all the Error details of the Exception that occured at the Client:",
            "updated": 1611154675224
        },
        {
            "style": "Placeholder",
            "text": "errorDetails",
            "updated": 1611154555419
        },
        {
            "style": "Text",
            "text": ""
        }
    ]
}